class Commando < Formula
  desc "Colorful TUI that turns a command's man page into a form for its options"
  homepage "https://github.com/lonedevel/commando"
  license "Apache-2.0"

  head do
    url "https://github.com/lonedevel/commando.git", branch: "main"
    depends_on "go" => :build
  end

  # Generated by scripts/update-formula.sh from the release's checksums.txt.
  on_macos do
    on_arm do
      url "https://github.com/lonedevel/commando/releases/download/v0.11.0/commando_0.11.0_darwin_arm64.tar.gz"
      sha256 "7a39b717d086ada01522134659c1203c7303e2adcdcd5306e667488a9fd5839b"
    end
    on_intel do
      url "https://github.com/lonedevel/commando/releases/download/v0.11.0/commando_0.11.0_darwin_amd64.tar.gz"
      sha256 "c4db22385a7667d7dc4465f0a038765fff7bc3453f6a81c4b8b509abc9e1810a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lonedevel/commando/releases/download/v0.11.0/commando_0.11.0_linux_arm64.tar.gz"
      sha256 "5c336897c624d2f77baffd861540f10245db4ab9ead541e27c11764aec2a17c5"
    end
    on_intel do
      url "https://github.com/lonedevel/commando/releases/download/v0.11.0/commando_0.11.0_linux_amd64.tar.gz"
      sha256 "6aa8356d0872092d75119ee0f578b2c3696138736644c871985e237e8275abc3"
    end
  end

  def install
    if build.head?
      system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}"), "./cmd/commando"
    else
      bin.install "commando"
    end
  end

  def caveats
    <<~EOS
      To edit the command you're typing with Ctrl-X Ctrl-O, add to your shell config:
        zsh:  eval "$(commando --init zsh)"
        bash: eval "$(commando --init bash)"
        fish: commando --init fish | source
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/commando --version")
    assert_match "bindkey", shell_output("#{bin}/commando --init zsh")

    # Parse a manual without needing a terminal.
    ENV["COMMANDO_CACHE_DIR"] = testpath/"cache"
    output = shell_output("#{bin}/commando --dump --no-cache ls")
    assert_match "\"names\"", output
  end
end
