class Commando < Formula
  desc "Colorful TUI that turns a command's man page into a form for its options"
  homepage "https://github.com/lonedevel/commando"
  license "Apache-2.0"

  head do
    url "https://github.com/lonedevel/commando.git", branch: "main"
    depends_on "go" => :build
  end

  # Generated by scripts/update-formula.sh from the release's checksums.txt.
  on_macos do
    on_arm do
      url "https://github.com/lonedevel/commando/releases/download/v0.9.0/commando_0.9.0_darwin_arm64.tar.gz"
      sha256 "8ffc3106ecaa5d25a7e762eacaea0f72886432b4b5b8ee4b13081c848e2e08f7"
    end
    on_intel do
      url "https://github.com/lonedevel/commando/releases/download/v0.9.0/commando_0.9.0_darwin_amd64.tar.gz"
      sha256 "0c387ab2317c8a22c6590cd2133fa822a2161dc574388e918df11299b480e465"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lonedevel/commando/releases/download/v0.9.0/commando_0.9.0_linux_arm64.tar.gz"
      sha256 "5024e7103431510d3faa55b528978c25c29f7c0863dd66dd68764d719cb10d76"
    end
    on_intel do
      url "https://github.com/lonedevel/commando/releases/download/v0.9.0/commando_0.9.0_linux_amd64.tar.gz"
      sha256 "b073c5ef1851dcc79ad26f5836e52af29cfdeca1d4431ce8f918f282c607bbf4"
    end
  end

  def install
    if build.head?
      system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}"), "./cmd/commando"
    else
      bin.install "commando"
    end
  end

  def caveats
    <<~EOS
      To edit the command you're typing with Ctrl-X Ctrl-O, add to your shell config:
        zsh:  eval "$(commando --init zsh)"
        bash: eval "$(commando --init bash)"
        fish: commando --init fish | source
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/commando --version")
    assert_match "bindkey", shell_output("#{bin}/commando --init zsh")

    # Parse a manual without needing a terminal.
    ENV["COMMANDO_CACHE_DIR"] = testpath/"cache"
    output = shell_output("#{bin}/commando --dump --no-cache ls")
    assert_match "\"names\"", output
  end
end
