class Commando < Formula
  desc "Colorful TUI that turns a command's man page into a form for its options"
  homepage "https://github.com/lonedevel/commando"
  license "Apache-2.0"

  head do
    url "https://github.com/lonedevel/commando.git", branch: "main"
    depends_on "go" => :build
  end

  # Generated by scripts/update-formula.sh from the release's checksums.txt.
  on_macos do
    on_arm do
      url "https://github.com/lonedevel/commando/releases/download/v0.6.0/commando_0.6.0_darwin_arm64.tar.gz"
      sha256 "85735d0a3d6f45133d819132dbbbbcef033fe6594d91735ee51946a44f51e152"
    end
    on_intel do
      url "https://github.com/lonedevel/commando/releases/download/v0.6.0/commando_0.6.0_darwin_amd64.tar.gz"
      sha256 "ecbe537666774616bcf8b9188a6f2c52c1f88ffa5adccb46dcde3f2251c92ae0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lonedevel/commando/releases/download/v0.6.0/commando_0.6.0_linux_arm64.tar.gz"
      sha256 "b5d4feb72bfb8eff8cd4929d7754beea096e8ab83949a47d3e26bedc94ae655a"
    end
    on_intel do
      url "https://github.com/lonedevel/commando/releases/download/v0.6.0/commando_0.6.0_linux_amd64.tar.gz"
      sha256 "49a72462b0f06bc1911d423067f7c7c6f48e5f6268c97b83a5601dddcd0c9eea"
    end
  end

  def install
    if build.head?
      system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}"), "./cmd/commando"
    else
      bin.install "commando"
    end
  end

  def caveats
    <<~EOS
      To edit the command you're typing with Ctrl-X Ctrl-O, add to your shell config:
        zsh:  eval "$(commando --init zsh)"
        bash: eval "$(commando --init bash)"
        fish: commando --init fish | source
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/commando --version")
    assert_match "bindkey", shell_output("#{bin}/commando --init zsh")

    # Parse a manual without needing a terminal.
    ENV["COMMANDO_CACHE_DIR"] = testpath/"cache"
    output = shell_output("#{bin}/commando --dump --no-cache ls")
    assert_match "\"names\"", output
  end
end
