#!/bin/sh
# Regenerates Formula/commando.rb for a published release, using the
# prebuilt archives' checksums from the release's checksums.txt.
#
#   scripts/update-formula.sh 0.2.0
#   scripts/update-formula.sh 0.2.0 dist/checksums.txt   # use a local file
set -eu
version=$1
repo=https://github.com/lonedevel/commando
base=$repo/releases/download/v$version
if [ $# -ge 2 ]; then
	sums=$(cat "$2")
else
	sums=$(curl -fsSL "$base/checksums.txt")
fi

sha() {
	s=$(printf '%s\n' "$sums" | awk -v f="commando_${version}_$1.tar.gz" '$2 == f { print $1 }')
	if [ -z "$s" ]; then
		echo "update-formula: no checksum for commando_${version}_$1.tar.gz" >&2
		exit 1
	fi
	printf '%s' "$s"
}

darwin_arm64=$(sha darwin_arm64)
darwin_amd64=$(sha darwin_amd64)
linux_arm64=$(sha linux_arm64)
linux_amd64=$(sha linux_amd64)

cat > "$(dirname "$0")/../Formula/commando.rb" <<RUBY
class Commando < Formula
  desc "Colorful TUI that turns a command's man page into a form for its options"
  homepage "$repo"
  license "Apache-2.0"

  head do
    url "$repo.git", branch: "main"
    depends_on "go" => :build
  end

  # Generated by scripts/update-formula.sh from the release's checksums.txt.
  on_macos do
    on_arm do
      url "$base/commando_${version}_darwin_arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "$base/commando_${version}_darwin_amd64.tar.gz"
      sha256 "$darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$base/commando_${version}_linux_arm64.tar.gz"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "$base/commando_${version}_linux_amd64.tar.gz"
      sha256 "$linux_amd64"
    end
  end

  def install
    if build.head?
      system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}"), "./cmd/commando"
      man1.install "docs/commando.1"
    else
      bin.install "commando"
      man1.install "commando.1"
    end
    generate_completions_from_executable(bin/"commando", "--completion")
  end

  def caveats
    <<~EOS
      To edit the command you're typing with Ctrl-X Ctrl-O, add to your shell config:
        zsh:  eval "\$(commando --init zsh)"
        bash: eval "\$(commando --init bash)"
        fish: commando --init fish | source
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/commando --version")
    assert_match "bindkey", shell_output("#{bin}/commando --init zsh")
    assert_match "compdef", shell_output("#{bin}/commando --completion zsh")
    assert_path_exists man1/"commando.1"

    # Parse a manual without needing a terminal.
    ENV["COMMANDO_CACHE_DIR"] = testpath/"cache"
    output = shell_output("#{bin}/commando --dump --no-cache ls")
    assert_match "\\"names\\"", output
  end
end
RUBY
echo "Formula/commando.rb now installs v$version"
